### ISSUE TITLE
Restore restart-scenarios-test.py

### ISSUE THREAD

**Issue by s-medvedev** [cyberway/cyberway#490]
**Update:** the test should be run with at least 2 producing nodes (`-p 2`).
It works with `resync` strategy, but fails with `none` and `hardReplay`

***
*old:*
Test not worked on EOS
```
Spread funds and validate
transaction[rows][0][balance] not found. Transaction: None
 Test failed.
 Shut down the cluster.
 Shut down the wallet.
  Killing wallet manager process 10877
Traceback (most recent call last):
  File "./tests/restart-scenarios-test.py", line 108, in <module>
	if not cluster.spreadFundsAndValidate(10):
  File "/mnt/working/eos.git/build/tests/Cluster.py", line 689, in spreadFundsAndValidate
	initialBalances=self.nodes[0].getEosBalances([self.defproduceraAccount] + self.accounts)
  File "/mnt/working/eos.git/build/tests/Node.py", line 779, in getEosBalances
	balance = self.getAccountEosBalance(account.name)
  File "/mnt/working/eos.git/build/tests/Node.py", line 861, in getAccountEosBalance
	balanceStr=self.getAccountEosBalanceStr(scope)
  File "/mnt/working/eos.git/build/tests/Node.py", line 854, in getAccountEosBalanceStr
	amount=self.getTableAccountBalance("eosio.token", scope)
  File "/mnt/working/eos.git/build/tests/Node.py", line 598, in getTableAccountBalance
	return trans["rows"][0]["balance"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by zxcat** [comment]
PR #1047
